### ISSUE TITLE
Outbound traffic

### ISSUE THREAD

**Issue by SergkeiM** [haimgel/do-floating-ip-k8s#1]
Hi @haimgel can this be used for outbound traffic via floating IP?

**Comment by haimgel** [comment]
@Froxz,
Unfortunately, no. Or at least I didn't find a way to do that. There's a ticket in DOKS for a related feature: https://github.com/digitalocean/DOKS/issues/9

**Comment by SergkeiM** [comment]
Hi @haimgel thank you for your reply.

Yes I'm subscribed to that ticket/issue :)

From what I understood to use floating IP for outbound we can use [this](https://docs.digitalocean.com/products/networking/floating-ips/how-to/outbound-traffic/) (on Normal droplet).

But of course, on DOKS it will be hard to apply this on the actual node, especially if using autoscale.


I was also thinking of creating a standard Droplet and forwarding all cluster outbound traffic via VPC to that droplet.

pod (app) -> VPC -> Droplet -> Internet.

But my knowledge of k8s is not strong, to make such a setup, so I will wait for DOKS to implement NAT Gateway.
